services:
  kafka:
    image: apache/kafka:3.7.1
    container_name: urbanhub-kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
    volumes:
      - kafka_data:/tmp/kraft-combined-logs

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: urbanhub-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: urbanhub-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  alert-service:
    build: ./alert-service
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    environment:
      ALERT_ENABLE_KAFKA_BRIDGE: "true"
      ALERT_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ALERT_WATER_QUALITY_TOPIC: mesure.qualite.eau
      ALERT_POLLUTION_ALERT_TOPIC: alerte.pollution.detectee
      ALERT_KAFKA_CONSUMER_GROUP: alert-service-consumer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  iot-service:
    build: ./iot-service
    depends_on:
      - kafka
    ports:
      - "8001:8001"
    environment:
      IOT_ENABLE_KAFKA: "true"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      WATER_QUALITY_TOPIC: mesure.qualite.eau
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  kafka_data:
