[project]
name = "urbanhub"
version = "0.1.1"
description = "UrbanHub Smart City platform"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "confluent-kafka>=2.13.0",
]

[dependency-groups]
dev = [
    "black>=26.3.1",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
]

[tool.black]
target-version = ["py313"]
