{
 "title": "UrbanHub Water Quality",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Alert Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"docker\", container=\"xtreme-programming-alert-service-1\"}"
    }
   ]
  },
  {
   "title": "IoT Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"docker\", container=\"xtreme-programming-iot-service-1\"}"
    }
   ]
  },
  {
   "title": "Kafka Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"docker\", container=\"xtreme-programming-kafka-1\"}"
    }
   ]
  }
 ]
}